name: Deploy to GitHub Pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v3.0.3
          with:
            # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x
            dotnet-version: 7.0
        - name: Publish .NET Core Project
          run: dotnet publish FAKA.Client.csproj -c Release -o release --nologo
        - name: download ssr 404 fix from github
          run: wget -P release/wwwroot "https://raw.githubusercontent.com/rafgraph/spa-github-pages/gh-pages/404.html"
        - name: Deploy GitHub Pages site
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: release/wwwroot
